name: R-Vocabular CI/CD

concurrency: production

on:
  push:
    branches:
      - main

jobs:

  Deploy:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{secrets.RV_VM}}
          HOST_NAME: ${{secrets.HOST_NAME}}
          USER_NAME: ${{secrets.USER_NAME}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          sh dotnet/RVocabular/build.sh
